

subroutine energy


! ******************************************************
! ***   FIND DENSITY AND CURRENT IN PHYSICAL SPACE   ***
! ******************************************************
!
! This subroutine integrates over all phase space
! to the energy.  This quantity is defined as:
!
!            /
! Energy  =  | (p**2/2 + phi_ext(r) + L**2/(2 r**2) + phi_self(r)/2 ) f 8 pi**2 L dr dp dL
!            /
!
! The self-gravity potential carries a factor 1/2. Summing phi_self over
! particles counts the interaction of every pair twice, once from each side;
! the energy of a self-gravitating system is (1/2) Int rho phi_self. Without
! the 1/2 the sum is not conserved: it changes by (1/2) Delta W_self whenever
! the mass is redistributed, an error of relative size ~a0 that no refinement
! of the discretization removes. The external background and the centrifugal
! term are not generated by the particles and take no factor.

! Include modules.

  use parameters
  use arrays
  use functions
  use utils
!$ use omp_lib
! Declare variables.

  implicit none

  integer i,j
  integer :: nth,tid
  real(8) :: lk,lp,le                        ! Partial sums of one thread
  real(8), allocatable :: part(:,:)
  real(8) :: smallpi,factor

  smallpi = acos(-1.0d0)


! Zero Angular Momentum
!  if (Lfix == 0.0d0) then

!     factor = 1.0d0

! Include Angular Momentum
!  else

     factor = 8.D0*smallpi**2*drc*dpc*dlc

!  endif  

  total_energy = 0.0D0
  kinetic = 0.D0
  potential = 0.D0

! Each thread sums its share into local accumulators, added afterwards in
! thread order: an OpenMP reduction combines them in the order the threads
! finish, which changed the energies at 1e-16 from run to run. This way they
! are the same to the last bit for a given number of threads.

  nth = 1
!$ nth = omp_get_max_threads()
  allocate(part(3,0:nth-1))
  part = 0.0D0

  !$OMP PARALLEL PRIVATE(i,tid,lk,lp,le)
  lk = 0.0D0
  lp = 0.0D0
  le = 0.0D0
  !$OMP DO SCHEDULE(STATIC)
  do i=1,Npart
    lk = lk + 0.5D0*p_part(i)**2*f(i)*l_part(i)
    lp = lp + (pot_part(i) - 0.5D0*potself_part(i))*f(i)*l_part(i)
    le = le + (0.5D0*p_part(i)**2 + pot_part(i) - 0.5D0*potself_part(i))*f(i)*l_part(i)
  end do
  !$OMP END DO
  tid = 0
!$ tid = omp_get_thread_num()
  part(:,tid) = [lk,lp,le]
  !$OMP END PARALLEL

  do tid=0,nth-1
    kinetic      = kinetic + part(1,tid)
    potential    = potential + part(2,tid)
    total_energy = total_energy + part(3,tid)
  end do
  deallocate(part)

  kinetic   = factor * kinetic
  potential = factor * potential
  total_energy    = factor * total_energy

end subroutine energy
